### ISSUE TITLE
`config_multicolorled` is unused?

### ISSUE THREAD

**Issue by shripal17** [BlissRoms/Documentation#4]
The documentation specifies to add `config_multicolorled` overlay for xiaomi devices, whereas this overlay is not used in the source.
Instead, `config_multiColorBatteryLed` is used in framework overlay

Also, as per `adb shell cmd overlay dump`, it says this resource was not found:
```
IDMAP OF com.android.frameworksres.overlay.phoenix
Paths:
    target path  : /system/framework/framework-res.apk
    overlay path : /vendor/overlay/FrameworksResOverlayPhoenix.apk
Debug info:
    ...
    W failed to find resource 'bool/config_multicolorled'
    ...
```

It would be better to update the documentation.

**Comment by StudioKeys** [comment]
Updated the new ones
